apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: battery-digital-twin
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/battery-digital-twin.git
    targetRevision: HEAD
    path: infrastructure/kubernetes
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true